# Generated by Django 4.2.7 on 2023-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('details', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=150)),
                ('vender_code', models.CharField(default='D60244', max_length=30)),
            ],
        ),
    ]
