# Generated by Django 4.2.7 on 2023-12-02 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venderprofile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='venderprofile',
            name='details',
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='average_response_time',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='contact_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='fulfillment_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='quality_rating_avg',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='venderprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='venderprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='venderprofile',
            name='vender_code',
            field=models.CharField(default='3505E9', max_length=30),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('po_number', models.CharField(default=uuid.UUID('639e9b1f-e09e-4e42-af4e-6a5df9bbf5ae'), max_length=50)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('order_completed_date', models.DateTimeField()),
                ('quality_rating', models.FloatField(default=0, null=True)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vender.venderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(default=0)),
                ('quality_rating_avg', models.FloatField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('fulfillment_rate', models.FloatField(default=0)),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vender.venderprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
