# Generated by Django 4.2.7 on 2023-12-02 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_remove_venderprofile_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=uuid.UUID('1ce996c6-f199-49e6-b027-994a5c066eac'), max_length=50),
        ),
        migrations.AlterField(
            model_name='venderprofile',
            name='vender_code',
            field=models.CharField(default='858931', max_length=30),
        ),
    ]
