# Generated by Django 4.2.7 on 2023-12-02 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0004_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(default=uuid.UUID('9063199e-e696-4e38-9a9e-7e291c99fba1'), max_length=50),
        ),
        migrations.AlterField(
            model_name='venderprofile',
            name='vender_code',
            field=models.CharField(default='DAA988', max_length=30),
        ),
    ]
